# Generated by Django 2.0 on 2018-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20180205_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_12v12',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
